[font]
size = 11.0

[font.normal]
family = "FiraCodeNerdFont"
style = "Regular"

[font.bold]
family = "FiraCodeNerdFont"
style = "Bold"

[font.italic]
family = "FiraCodeNerdFont"
style = "Italic"  # Fira Code doesn't have true italics

[font.bold_italic]
family = "FiraCodeNerdFont" 
style = "Bold"  # Using Bold as fallback for bold italic

# Offset settings
[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

# Enable ligatures - correct syntax for newer Alacritty versions
[terminal]

# Other recommended settings
[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[window]
padding = { x = 8, y = 8 }
opacity = 0.95

