# Helix Editor Configuration

# Theme
theme = "catppuccin_mocha"

# Editor Settings
[editor]
line-number = "relative"
cursorline = true
mouse = false
color-modes = true
end-of-line-diagnostics = "hint"
auto-save = true
# rulers = [80, 120]
cursorcolumn = true
bufferline = "always"

# Cursor Configuration
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Text Wrapping
[editor.soft-wrap]
enable = true
wrap-indicator = "↩"

# Whitespace Visualization
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

# Status Line Configuration
[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "separator", "version-control", "separator"]
right = ["position", "position-percentage", "total-line-numbers"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# Indentation Guides
[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

# Diagnostics and LSP
[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

# File Picker Settings
[editor.file-picker]
# hidden = false
git-ignore = false

# Keybindings - Normal Mode
[keys.normal]
ins = "insert_mode"
esc = ["collapse_selection", "keep_primary_selection"]
C-o = ":open ~/.config/helix/config.toml"
C-r = ":config-reload"
p = ":clipboard-paste-after"
home = "goto_first_nonwhitespace"
space.c = "toggle_comments"
X = "extend_line_above"
D = ["extend_to_line_end", "change_selection"]
tab = "half_page_down"
"S-tab" = "half_page_up"
y = "yank_main_selection_to_clipboard"
space.x = ":toggle whitespace.render all none"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-A-down = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
S-A-up = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]
space."." = "file_picker_in_current_buffer_directory"

# Keybindings - Insert Mode
[keys.insert]
ins = "normal_mode"
home = "goto_first_nonwhitespace"
S-A-down = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
S-A-up = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]

# Keybindings - Select Mode
[keys.select]
ins = "normal_mode"
