[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
formatter = ["gofmt"]
comment-token = "//"
language-servers = [ "gopls", "golangci-lint-lsp" ]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]

[[language]]
name = "json"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "json", "-c", "~/git/dprint.json"]}
file-types = ["json"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md", "-c", "~/git/dprint.json"]}
file-types = ["md"]

[[language]]
name = "python"
auto-format = true
# diagnostic-severity="warning"
language-servers = ["pyright","ruff"]
indent = { tab-width = 4, unit = "    " }

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=88"
]

[language-server.pyright]
# command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true
reportUnusedVariable = true

[language-server.bun]
command = "bun"
args = ["bun", "lsp"]

[[language]]
name = "typescript"
language-servers = ["bun"]
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "ts", "-c", "~git/dprint.json"]}
file-types = ["tsx", "ts"]

[[language]]
name = "rust"
auto-format = true

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
