[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
formatter = ["gofmt"]
comment-token = "//"
language-servers = [ "gopls", "golangci-lint-lsp" ]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]

[[language]]
name = "json"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "json", "-c", "~/git/dprint.json"]}
file-types = ["json"]

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md", "-c", "~/git/dprint.json"]}
file-types = ["md"]

[[language]]
name = "python"
auto-format = true
# diagnostic-severity="warning"
language-servers = ["pyright","ruff"]
indent = { tab-width = 4, unit = "    " }

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=88"
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true
reportUnusedVariable = true

[language-server.bun]
command = "bun"
args = ["bun", "lsp"]

[[language]]
name = "typescript"
language-servers = ["bun"]
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "ts", "-c", "~git/dprint.json"]}
file-types = ["tsx", "ts"]

[[language]]
name = "sql"
auto-format = true
formatter = { command = "sqlfluff", args = ["fix"]}
file-types = ["sql"]

[[language]]
name = "hcl"
scope = "source.hcl"
injection-regex = "(hcl|tf|nomad)"
language-id = "terraform"
file-types = ["hcl", "tf", "nomad", "tfvars"]
comment-token = "#"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 2, unit = "  " }
language-servers = [ "terraform-ls" ]
auto-format = true
